package com.mediconnect.consultation.dto;
import java.util.List;
public record IntakeFormRequest(
    String chiefComplaint,
    String symptomDuration,
    String currentMedications,
    String allergies,
    String additionalNotes,
    List<SymptomEntry> symptoms,
    Double temperature,
    String bloodPressure,
    Double bloodGlucose,
    String bodyZone,
    String bodyZoneSymptoms,
    String symptomOnset,
    String painIntensity,
    String painType,
    Boolean hadSymptomsBefore,
    String generalSymptoms,
    String medicationsTakenText,
    String knownConditions
) {}
